### ISSUE TITLE
版式还原

### ISSUE THREAD

**Issue by BrightXiaoHan** [RapidAI/RapidOCRPDF#1]
请问会更新版式还原功能么

**Comment by SWHL** [comment]
如果是可以直接复制的PDF，请直接使用[pdf2docx](https://github.com/dothinking/pdf2docx)
如果是扫描版的PDF，后续会更新的，时间不定哈

**Comment by spphinslove** [comment]
这要做出来了，就不用看扫描版的了。

**Comment by SWHL** [comment]
实际上，结合[RapidStructure](https://github.com/RapidAI/RapidStructure)中已有的功能块，已经可以做的。
感兴趣的小伙伴，可以自己尝试尝试

**Comment by pjhcsz** [comment]
我在centos7上安装了，运行的时候一直报错：Exception ignored in: <function Document.__del__ at 0x000001607F39EF70>
AttributeError: 'Document' object has no attribute 'is_closed'，然后我安装了fitz库，还是不行，求大神解答

**Comment by SWHL** [comment]
@pjhcsz 在新的issue里说吧，当前issue和你的问题关系不大哈
新issue [#9](https://github.com/RapidAI/RapidOCRPDF/issues/9)

**Comment by SWHL** [comment]
参见最新项目：https://github.com/RapidAI/RapidLayoutRecover
