### ISSUE TITLE
pdf去除页眉页脚

### ISSUE THREAD

**Issue by li-wen22** [RapidAI/RapidOCRPDF#10]
在解析pdf的时候，解析出的文字信息会包含页眉页脚，使得全文并不通畅，这个有合适的解决思路吗？谢谢

**Comment by SWHL** [comment]
这个可以用版面分析模型提前过滤一下。可以参见[`rapid_layout`](https://github.com/RapidAI/RapidStructure/blob/main/docs/README_Layout.md)
