### ISSUE TITLE
M1 硬件不支持

### ISSUE THREAD

**Issue by username12021202** [RapidAI/RapidOCRPDF#16]
➜  ~ pip3 install rapidocr_pdf==0.0.4
Collecting rapidocr_pdf==0.0.4
  Using cached rapidocr_pdf-0.0.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: filetype in /opt/homebrew/lib/python3.11/site-packages (from rapidocr_pdf==0.0.4) (1.2.0)
Requirement already satisfied: pymupdf in /opt/homebrew/lib/python3.11/site-packages (from rapidocr_pdf==0.0.4) (1.24.4)
Requirement already satisfied: PyMuPDFb==1.24.3 in /opt/homebrew/lib/python3.11/site-packages (from pymupdf->rapidocr_pdf==0.0.4) (1.24.3)
Using cached rapidocr_pdf-0.0.4-py3-none-any.whl (8.6 kB)
Installing collected packages: rapidocr_pdf
Successfully installed rapidocr_pdf-0.0.4
➜  ~ python3
Python 3.11.4 (main, Jul 25 2023, 16:35:02) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> rapidocr_pdf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'rapidocr_pdf' is not defined
>>>
>>>
>>> import rapidocr_pdf
[1]    39499 illegal hardware instruction  /opt/homebrew/bin/python3.11

**Comment by SWHL** [comment]
从你发的信息，看不出来是具体是哪个包不支持。可否验证一下以下是哪个包在你的环境下有问题吗？
```text
filetype>=1.2.0
pymupdf
rapidocr_onnxruntime
```

**Comment by username12021202** [comment]
我升级了MacOS之后，解决了这个问题。原有的操作系统是 11.5.2。现在升级到了，14.5 (23F79)

**Comment by SWHL** [comment]
好的

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月28日 15:03 |
| 收件人 | RapidAI/RapidOCRPDF ***@***.***> |
| 抄送人 | SWHL ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [RapidAI/RapidOCRPDF] M1 硬件不支持 (Issue #16) |

我升级了MacOS之后，解决了这个问题。原有的操作系统是 11.5.2。现在升级到了，14.5 (23F79)
