### ISSUE TITLE
无法安装rapidocr_pdf

### ISSUE THREAD

**Issue by Sherlockqhs** [RapidAI/RapidOCRPDF#18]
使用pip install rapidocr_pdf 或者 pip install -i https://pypi.tuna.tsinghua.edu.cn/simple rapidocr_pdf 均无法正常安装，报错如下：
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.6,<=3.10; 0.0.2 Requires-Python >=3.7,<=3.10; 0.0.3 Requires-Python >=3.7,<=3.10; 0.0.4 Requires-Python >=3.6,<3.12; 0.0.5 Requires-Python >=3.6,<3.12; 0.0.6 Requires-Python >=3.6,<3.12; 0.0.7 Requires-Python >=3.6,<3.12; 0.0.8 Requires-Python >=3.6,<3.12; 0.1.0 Requires-Python <3.12,>=3.6
ERROR: Could not find a version that satisfies the requirement rapidocr_pdf (from versions: none)
ERROR: No matching distribution found for rapidocr_pdf

**Comment by SWHL** [comment]
python版本要在3.6和3.12之间。建议3.10再试
