### ISSUE TITLE
依赖包冲突

### ISSUE THREAD

**Issue by imClumsyPanda** [RapidAI/RapidOCRPDF#2]
在macOS中安装rapidocrpdf时发生依赖冲突报错

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
paddleocr 2.7.0.2 requires PyMuPDF<1.21.0, but you have pymupdf 1.22.5 which is incompatible.

**Comment by SWHL** [comment]
已经在`v0.0.6`中修复了，请直接`pip install rapidocr_pdf==v0.0.6`安装，再次尝试即可。

**Comment by imClumsyPanda** [comment]
感谢🙏
