### ISSUE TITLE
pdfextractor 不能强制OCR pdf所有页面吗？

### ISSUE THREAD

**Issue by yonglee7015** [RapidAI/RapidOCRPDF#3]
我有些pdf页面是文字和扫描或者图片混合的，可以有参数设置每页都强制OCR识别吗？类似于ocrmypdf force_ocr的。

**Comment by SWHL** [comment]
这个后续我考虑加一下，欢迎提PR

**Comment by SWHL** [comment]
已经在`rapidocr_pdf>=0.0.7`中实现
