### ISSUE TITLE
AttributeError: 'Document' object has no attribute 'is_closed'

### ISSUE THREAD

**Issue by SWHL** [RapidAI/RapidOCRPDF#9]
我在centos7上安装了，运行的时候一直报错：Exception ignored in: <function Document.__del__ at 0x000001607F39EF70>
AttributeError: 'Document' object has no attribute 'is_closed'，然后我安装了fitz库，还是不行，求大神解答

_Originally posted by @pjhcsz in https://github.com/RapidAI/RapidOCRPDF/issues/1#issuecomment-1915899121_

**Comment by SWHL** [comment]
请提供具体python、PyMuPDF版本信息，以及测试代码和报错信息，便于复现和排查。 @pjhcsz

**Comment by pjhcsz** [comment]
Python3.9.6 --PyMuPDF1.18.9

**Comment by SWHL** [comment]
我这里并没有复现你的问题。可以参考PyMuPDF issue [#679](https://github.com/pymupdf/PyMuPDF/issues/679)

**Comment by pjhcsz** [comment]
感谢大神，我把PyMuPDF 升级到1.19.6问题就解决了

**Comment by SWHL** [comment]
好的，issue先关了，后续有问题再开。
